## Ejercicio hiperparametrización breast cancer de sklearn

1. Carga el dataset [breast_cancer de `sklearn`](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_breast_cancer.html)
2. Prueba al menos 5 modelos diferentes de clasificación y aplica un GridSearchCV mediante Pipelines. Aplica también un RandomizedSearchCV.
3. Conclusiones. Guarda el modelo final en un archivo con pickle.

In [1]:
import warnings

warnings.filterwarnings("ignore", category=DeprecationWarning)

In [2]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.datasets import load_breast_cancer

#### 1. Carga el dataset [breast_cancer de `sklearn`](https://scikit-learn.org/stable/modules/generated/sklearn.datasets.load_breast_cancer.html)

In [3]:
%matplotlib inline
data = load_breast_cancer()
data

{'data': array([[1.799e+01, 1.038e+01, 1.228e+02, ..., 2.654e-01, 4.601e-01,
         1.189e-01],
        [2.057e+01, 1.777e+01, 1.329e+02, ..., 1.860e-01, 2.750e-01,
         8.902e-02],
        [1.969e+01, 2.125e+01, 1.300e+02, ..., 2.430e-01, 3.613e-01,
         8.758e-02],
        ...,
        [1.660e+01, 2.808e+01, 1.083e+02, ..., 1.418e-01, 2.218e-01,
         7.820e-02],
        [2.060e+01, 2.933e+01, 1.401e+02, ..., 2.650e-01, 4.087e-01,
         1.240e-01],
        [7.760e+00, 2.454e+01, 4.792e+01, ..., 0.000e+00, 2.871e-01,
         7.039e-02]], shape=(569, 30)),
 'target': array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1,
        0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 1, 1, 1, 1, 0, 1, 0, 0,
        1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 0, 0,
        1, 1, 1, 0, 1, 1, 0, 0, 1, 1, 1, 0, 0, 1, 1, 1, 1, 0, 1, 1, 0, 1,
        1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 1, 0, 0, 1, 1, 1, 0, 0, 1, 0, 1, 0,
        0, 1, 0, 0, 1, 1, 0, 1, 1, 0, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 0, 1, 1, 1, 1, 0, 0, 1, 0, 1, 1, 0, 0, 1, 1, 0, 0, 1, 1, 1,
        1, 0, 1, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 0, 0,
        0, 0, 1, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 0, 0, 0, 0, 1, 1, 0, 0,
        1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 1, 0, 1, 1, 0, 0, 1, 0, 1, 1,
        1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
        0, 0, 1, 1, 1, 1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0, 1, 0, 0, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 0, 1, 1, 1, 1, 0, 0,
        0, 1, 1, 1, 1, 0, 1, 0, 1, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0,
        0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0, 0, 0, 1, 0, 0,
        1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 1, 1, 0, 0, 1, 1,
        1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 0,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 0, 1, 1, 1, 1,
        1, 0, 1, 1, 0, 1, 0, 1, 1, 0, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0,
        1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1,
        1, 1, 1, 0, 1, 0, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 1, 0, 1, 1,
        1, 1, 1, 0, 1, 1, 0, 1, 0, 1, 0, 0, 1, 1, 1, 0, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
        1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 1]),
 'frame': None,
 'target_names': array(['malignant', 'benign'], dtype='<U9'),
 'DESCR': '.. _breast_cancer_dataset:\n\nBreast cancer Wisconsin (diagnostic) dataset\n--------------------------------------------\n\n**Data Set Characteristics:**\n\n:Number of Instances: 569\n\n:Number of Attributes: 30 numeric, predictive attributes and the class\n\n:Attribute Information:\n    - radius (mean of distances from center to points on the perimeter)\n    - texture (standard deviation of gray-scale values)\n    - perimeter\n    - area\n    - smoothness (local variation in radius lengths)\n    - compactness (perimeter^2 / area - 1.0)\n    - concavity (severity of concave portions of the contour)\n    - concave points (number of concave portions of the contour)\n    - symmetry\n    - fractal dimension ("coastline approximation" - 1)\n\n    The mean, standard error, and "worst" or largest (mean of the three\n    worst/largest values) of these features were computed for each image,\n    resulting in 30 features.  For instance, field 0 is Mean Radius, field\n    10 is Radius SE, field 20 is Worst Radius.\n\n    - class:\n            - WDBC-Malignant\n            - WDBC-Benign\n\n:Summary Statistics:\n\n===================================== ====== ======\n                                        Min    Max\n===================================== ====== ======\nradius (mean):                        6.981  28.11\ntexture (mean):                       9.71   39.28\nperimeter (mean):                     43.79  188.5\narea (mean):                          143.5  2501.0\nsmoothness (mean):                    0.053  0.163\ncompactness (mean):                   0.019  0.345\nconcavity (mean):                     0.0    0.427\nconcave points (mean):                0.0    0.201\nsymmetry (mean):                      0.106  0.304\nfractal dimension (mean):             0.05   0.097\nradius (standard error):              0.112  2.873\ntexture (standard error):             0.36   4.885\nperimeter (standard error):           0.757  21.98\narea (standard error):                6.802  542.2\nsmoothness (standard error):          0.002  0.031\ncompactness (standard error):         0.002  0.135\nconcavity (standard error):           0.0    0.396\nconcave points (standard error):      0.0    0.053\nsymmetry (standard error):            0.008  0.079\nfractal dimension (standard error):   0.001  0.03\nradius (worst):                       7.93   36.04\ntexture (worst):                      12.02  49.54\nperimeter (worst):                    50.41  251.2\narea (worst):                         185.2  4254.0\nsmoothness (worst):                   0.071  0.223\ncompactness (worst):                  0.027  1.058\nconcavity (worst):                    0.0    1.252\nconcave points (worst):               0.0    0.291\nsymmetry (worst):                     0.156  0.664\nfractal dimension (worst):            0.055  0.208\n===================================== ====== ======\n\n:Missing Attribute Values: None\n\n:Class Distribution: 212 - Malignant, 357 - Benign\n\n:Creator:  Dr. William H. Wolberg, W. Nick Street, Olvi L. Mangasarian\n\n:Donor: Nick Street\n\n:Date: November, 1995\n\nThis is a copy of UCI ML Breast Cancer Wisconsin (Diagnostic) datasets.\nhttps://goo.gl/U2Uwz2\n\nFeatures are computed from a digitized image of a fine needle\naspirate (FNA) of a breast mass.  They describe\ncharacteristics of the cell nuclei present in the image.\n\nSeparating plane described above was obtained using\nMultisurface Method-Tree (MSM-T) [K. P. Bennett, "Decision Tree\nConstruction Via Linear Programming." Proceedings of the 4th\nMidwest Artificial Intelligence and Cognitive Science Society,\npp. 97-101, 1992], a classification method which uses linear\nprogramming to construct a decision tree.  Relevant features\nwere selected using an exhaustive search in the space of 1-4\nfeatures and 1-3 separating planes.\n\nThe actual linear program used to obtain the separating plane\nin the 3-dimensional space is that described in:\n[K. P. Bennett and O. L. Mangasarian: "Robust Linear\nProgramming Discrimination of Two Linearly Inseparable Sets",\nOptimization Methods and Software 1, 1992, 23-34].\n\nThis database is also available through the UW CS ftp server:\n\nftp ftp.cs.wisc.edu\ncd math-prog/cpo-dataset/machine-learn/WDBC/\n\n.. dropdown:: References\n\n  - W.N. Street, W.H. Wolberg and O.L. Mangasarian. Nuclear feature extraction\n    for breast tumor diagnosis. IS&T/SPIE 1993 International Symposium on\n    Electronic Imaging: Science and Technology, volume 1905, pages 861-870,\n    San Jose, CA, 1993.\n  - O.L. Mangasarian, W.N. Street and W.H. Wolberg. Breast cancer diagnosis and\n    prognosis via linear programming. Operations Research, 43(4), pages 570-577,\n    July-August 1995.\n  - W.H. Wolberg, W.N. Street, and O.L. Mangasarian. Machine learning techniques\n    to diagnose breast cancer from fine-needle aspirates. Cancer Letters 77 (1994)\n    163-171.\n',
 'feature_names': array(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
        'mean smoothness', 'mean compactness', 'mean concavity',
        'mean concave points', 'mean symmetry', 'mean fractal dimension',
        'radius error', 'texture error', 'perimeter error', 'area error',
        'smoothness error', 'compactness error', 'concavity error',
        'concave points error', 'symmetry error',
        'fractal dimension error', 'worst radius', 'worst texture',
        'worst perimeter', 'worst area', 'worst smoothness',
        'worst compactness', 'worst concavity', 'worst concave points',
        'worst symmetry', 'worst fractal dimension'], dtype='<U23'),
 'filename': 'breast_cancer.csv',
 'data_module': 'sklearn.datasets.data'}

In [4]:
data.keys()

dict_keys(['data', 'target', 'frame', 'target_names', 'DESCR', 'feature_names', 'filename', 'data_module'])

In [5]:
print(data['DESCR'])

.. _breast_cancer_dataset:

Breast cancer Wisconsin (diagnostic) dataset
--------------------------------------------

**Data Set Characteristics:**

:Number of Instances: 569

:Number of Attributes: 30 numeric, predictive attributes and the class

:Attribute Information:
    - radius (mean of distances from center to points on the perimeter)
    - texture (standard deviation of gray-scale values)
    - perimeter
    - area
    - smoothness (local variation in radius lengths)
    - compactness (perimeter^2 / area - 1.0)
    - concavity (severity of concave portions of the contour)
    - concave points (number of concave portions of the contour)
    - symmetry
    - fractal dimension ("coastline approximation" - 1)

    The mean, standard error, and "worst" or largest (mean of the three
    worst/largest values) of these features were computed for each image,
    resulting in 30 features.  For instance, field 0 is Mean Radius, field
    10 is Radius SE, field 20 is Worst Radius.

    - class:
            - WDBC-Malignant
            - WDBC-Benign

:Summary Statistics:

===================================== ====== ======
                                        Min    Max
===================================== ====== ======
radius (mean):                        6.981  28.11
texture (mean):                       9.71   39.28
perimeter (mean):                     43.79  188.5
area (mean):                          143.5  2501.0
smoothness (mean):                    0.053  0.163
compactness (mean):                   0.019  0.345
concavity (mean):                     0.0    0.427
concave points (mean):                0.0    0.201
symmetry (mean):                      0.106  0.304
fractal dimension (mean):             0.05   0.097
radius (standard error):              0.112  2.873
texture (standard error):             0.36   4.885
perimeter (standard error):           0.757  21.98
area (standard error):                6.802  542.2
smoothness (standard error):          0.002  0.031
compactness (standard error):         0.002  0.135
concavity (standard error):           0.0    0.396
concave points (standard error):      0.0    0.053
symmetry (standard error):            0.008  0.079
fractal dimension (standard error):   0.001  0.03
radius (worst):                       7.93   36.04
texture (worst):                      12.02  49.54
perimeter (worst):                    50.41  251.2
area (worst):                         185.2  4254.0
smoothness (worst):                   0.071  0.223
compactness (worst):                  0.027  1.058
concavity (worst):                    0.0    1.252
concave points (worst):               0.0    0.291
symmetry (worst):                     0.156  0.664
fractal dimension (worst):            0.055  0.208
===================================== ====== ======

:Missing Attribute Values: None

:Class Distribution: 212 - Malignant, 357 - Benign

:Creator:  Dr. William H. Wolberg, W. Nick Street, Olvi L. Mangasarian

:Donor: Nick Street

:Date: November, 1995

This is a copy of UCI ML Breast Cancer Wisconsin (Diagnostic) datasets.
https://goo.gl/U2Uwz2

Features are computed from a digitized image of a fine needle
aspirate (FNA) of a breast mass.  They describe
characteristics of the cell nuclei present in the image.

Separating plane described above was obtained using
Multisurface Method-Tree (MSM-T) [K. P. Bennett, "Decision Tree
Construction Via Linear Programming." Proceedings of the 4th
Midwest Artificial Intelligence and Cognitive Science Society,
pp. 97-101, 1992], a classification method which uses linear
programming to construct a decision tree.  Relevant features
were selected using an exhaustive search in the space of 1-4
features and 1-3 separating planes.

The actual linear program used to obtain the separating plane
in the 3-dimensional space is that described in:
[K. P. Bennett and O. L. Mangasarian: "Robust Linear
Programming Discrimination of Two Linearly Inseparable Sets",
Optimization Methods and Software 1, 1992, 23-34].

This database is also available through the UW CS ftp server:

ftp ftp.cs.wisc.edu
cd math-prog/cpo-dataset/machine-learn/WDBC/

.. dropdown:: References

  - W.N. Street, W.H. Wolberg and O.L. Mangasarian. Nuclear feature extraction
    for breast tumor diagnosis. IS&T/SPIE 1993 International Symposium on
    Electronic Imaging: Science and Technology, volume 1905, pages 861-870,
    San Jose, CA, 1993.
  - O.L. Mangasarian, W.N. Street and W.H. Wolberg. Breast cancer diagnosis and
    prognosis via linear programming. Operations Research, 43(4), pages 570-577,
    July-August 1995.
  - W.H. Wolberg, W.N. Street, and O.L. Mangasarian. Machine learning techniques
    to diagnose breast cancer from fine-needle aspirates. Cancer Letters 77 (1994)
    163-171.

In [6]:
df = pd.DataFrame(data['data'], columns=data['feature_names'])
df['target'] = data['target']
df

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
0,17.99,10.38,122.80,1001.0,0.11840,0.27760,0.30010,0.14710,0.2419,0.07871,...,17.33,184.60,2019.0,0.16220,0.66560,0.7119,0.2654,0.4601,0.11890,0
1,20.57,17.77,132.90,1326.0,0.08474,0.07864,0.08690,0.07017,0.1812,0.05667,...,23.41,158.80,1956.0,0.12380,0.18660,0.2416,0.1860,0.2750,0.08902,0
2,19.69,21.25,130.00,1203.0,0.10960,0.15990,0.19740,0.12790,0.2069,0.05999,...,25.53,152.50,1709.0,0.14440,0.42450,0.4504,0.2430,0.3613,0.08758,0
3,11.42,20.38,77.58,386.1,0.14250,0.28390,0.24140,0.10520,0.2597,0.09744,...,26.50,98.87,567.7,0.20980,0.86630,0.6869,0.2575,0.6638,0.17300,0
4,20.29,14.34,135.10,1297.0,0.10030,0.13280,0.19800,0.10430,0.1809,0.05883,...,16.67,152.20,1575.0,0.13740,0.20500,0.4000,0.1625,0.2364,0.07678,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
564,21.56,22.39,142.00,1479.0,0.11100,0.11590,0.24390,0.13890,0.1726,0.05623,...,26.40,166.10,2027.0,0.14100,0.21130,0.4107,0.2216,0.2060,0.07115,0
565,20.13,28.25,131.20,1261.0,0.09780,0.10340,0.14400,0.09791,0.1752,0.05533,...,38.25,155.00,1731.0,0.11660,0.19220,0.3215,0.1628,0.2572,0.06637,0
566,16.60,28.08,108.30,858.1,0.08455,0.10230,0.09251,0.05302,0.1590,0.05648,...,34.12,126.70,1124.0,0.11390,0.30940,0.3403,0.1418,0.2218,0.07820,0
567,20.60,29.33,140.10,1265.0,0.11780,0.27700,0.35140,0.15200,0.2397,0.07016,...,39.42,184.60,1821.0,0.16500,0.86810,0.9387,0.2650,0.4087,0.12400,0
568,7.76,24.54,47.92,181.0,0.05263,0.04362,0.00000,0.00000,0.1587,0.05884,...,30.37,59.16,268.6,0.08996,0.06444,0.0000,0.0000,0.2871,0.07039,1

In [7]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 569 entries, 0 to 568
Data columns (total 31 columns):
 #   Column                   Non-Null Count  Dtype
---  ------                   --------------  -----
 0   mean radius              569 non-null    float64
 1   mean texture             569 non-null    float64
 2   mean perimeter           569 non-null    float64
 3   mean area                569 non-null    float64
 4   mean smoothness          569 non-null    float64
 5   mean compactness         569 non-null    float64
 6   mean concavity           569 non-null    float64
 7   mean concave points      569 non-null    float64
 8   mean symmetry            569 non-null    float64
 9   mean fractal dimension   569 non-null    float64
 10  radius error             569 non-null    float64
 11  texture error            569 non-null    float64
 12  perimeter error          569 non-null    float64
 13  area error               569 non-null    float64
 14  smoothness error         569 non-null    float64
 15  compactness error        569 non-null    float64
 16  concavity error          569 non-null    float64
 17  concave points error     569 non-null    float64
 18  symmetry error           569 non-null    float64
 19  fractal dimension error  569 non-null    float64
 20  worst radius             569 non-null    float64
 21  worst texture            569 non-null    float64
 22  worst perimeter          569 non-null    float64
 23  worst area               569 non-null    float64
 24  worst smoothness         569 non-null    float64
 25  worst compactness        569 non-null    float64
 26  worst concavity          569 non-null    float64
 27  worst concave points     569 non-null    float64
 28  worst symmetry           569 non-null    float64
 29  worst fractal dimension  569 non-null    float64
 30  target                   569 non-null    int64
dtypes: float64(30), int64(1)
memory usage: 137.9 KB

In [8]:
df['target'].unique()

array([0, 1])

In [9]:
df.describe().T

,count,mean,std,min,25%,50%,75%,max
mean radius,569.0,14.127292,3.524049,6.981000,11.700000,13.370000,15.780000,28.11000
mean texture,569.0,19.289649,4.301036,9.710000,16.170000,18.840000,21.800000,39.28000
mean perimeter,569.0,91.969033,24.298981,43.790000,75.170000,86.240000,104.100000,188.50000
mean area,569.0,654.889104,351.914129,143.500000,420.300000,551.100000,782.700000,2501.00000
mean smoothness,569.0,0.096360,0.014064,0.052630,0.086370,0.095870,0.105300,0.16340
mean compactness,569.0,0.104341,0.052813,0.019380,0.064920,0.092630,0.130400,0.34540
mean concavity,569.0,0.088799,0.079720,0.000000,0.029560,0.061540,0.130700,0.42680
mean concave points,569.0,0.048919,0.038803,0.000000,0.020310,0.033500,0.074000,0.20120
mean symmetry,569.0,0.181162,0.027414,0.106000,0.161900,0.179200,0.195700,0.30400
mean fractal dimension,569.0,0.062798,0.007060,0.049960,0.057700,0.061540,0.066120,0.09744
radius error,569.0,0.405172,0.277313,0.111500,0.232400,0.324200,0.478900,2.87300
texture error,569.0,1.216853,0.551648,0.360200,0.833900,1.108000,1.474000,4.88500
perimeter error,569.0,2.866059,2.021855,0.757000,1.606000,2.287000,3.357000,21.98000
area error,569.0,40.337079,45.491006,6.802000,17.850000,24.530000,45.190000,542.20000
smoothness error,569.0,0.007041,0.003003,0.001713,0.005169,0.006380,0.008146,0.03113
compactness error,569.0,0.025478,0.017908,0.002252,0.013080,0.020450,0.032450,0.13540
concavity error,569.0,0.031894,0.030186,0.000000,0.015090,0.025890,0.042050,0.39600
concave points error,569.0,0.011796,0.006170,0.000000,0.007638,0.010930,0.014710,0.05279
symmetry error,569.0,0.020542,0.008266,0.007882,0.015160,0.018730,0.023480,0.07895
fractal dimension error,569.0,0.003795,0.002646,0.000895,0.002248,0.003187,0.004558,0.02984
worst radius,569.0,16.269190,4.833242,7.930000,13.010000,14.970000,18.790000,36.04000
worst texture,569.0,25.677223,6.146258,12.020000,21.080000,25.410000,29.720000,49.54000
worst perimeter,569.0,107.261213,33.602542,50.410000,84.110000,97.660000,125.400000,251.20000
worst area,569.0,880.583128,569.356993,185.200000,515.300000,686.500000,1084.000000,4254.00000
worst smoothness,569.0,0.132369,0.022832,0.071170,0.116600,0.131300,0.146000,0.22260
worst compactness,569.0,0.254265,0.157336,0.027290,0.147200,0.211900,0.339100,1.05800
worst concavity,569.0,0.272188,0.208624,0.000000,0.114500,0.226700,0.382900,1.25200
worst concave points,569.0,0.114606,0.065732,0.000000,0.064930,0.099930,0.161400,0.29100
worst symmetry,569.0,0.290076,0.061867,0.156500,0.250400,0.282200,0.317900,0.66380
worst fractal dimension,569.0,0.083946,0.018061,0.055040,0.071460,0.080040,0.092080,0.20750
target,569.0,0.627417,0.483918,0.000000,0.000000,1.000000,1.000000,1.00000

In [10]:
df.corr(numeric_only=True).round(3)

,mean radius,mean texture,mean perimeter,mean area,mean smoothness,mean compactness,mean concavity,mean concave points,mean symmetry,mean fractal dimension,...,worst texture,worst perimeter,worst area,worst smoothness,worst compactness,worst concavity,worst concave points,worst symmetry,worst fractal dimension,target
mean radius,1.000,0.324,0.998,0.987,0.171,0.506,0.677,0.823,0.148,-0.312,...,0.297,0.965,0.941,0.120,0.413,0.527,0.744,0.164,0.007,-0.730
mean texture,0.324,1.000,0.330,0.321,-0.023,0.237,0.302,0.293,0.071,-0.076,...,0.912,0.358,0.344,0.078,0.278,0.301,0.295,0.105,0.119,-0.415
mean perimeter,0.998,0.330,1.000,0.987,0.207,0.557,0.716,0.851,0.183,-0.261,...,0.303,0.970,0.942,0.151,0.456,0.564,0.771,0.189,0.051,-0.743
mean area,0.987,0.321,0.987,1.000,0.177,0.499,0.686,0.823,0.151,-0.283,...,0.287,0.959,0.959,0.124,0.390,0.513,0.722,0.144,0.004,-0.709
mean smoothness,0.171,-0.023,0.207,0.177,1.000,0.659,0.522,0.554,0.558,0.585,...,0.036,0.239,0.207,0.805,0.472,0.435,0.503,0.394,0.499,-0.359
mean compactness,0.506,0.237,0.557,0.499,0.659,1.000,0.883,0.831,0.603,0.565,...,0.248,0.590,0.510,0.566,0.866,0.816,0.816,0.510,0.687,-0.597
mean concavity,0.677,0.302,0.716,0.686,0.522,0.883,1.000,0.921,0.501,0.337,...,0.300,0.730,0.676,0.449,0.755,0.884,0.861,0.409,0.515,-0.696
mean concave points,0.823,0.293,0.851,0.823,0.554,0.831,0.921,1.000,0.462,0.167,...,0.293,0.856,0.810,0.453,0.667,0.752,0.910,0.376,0.369,-0.777
mean symmetry,0.148,0.071,0.183,0.151,0.558,0.603,0.501,0.462,1.000,0.480,...,0.091,0.219,0.177,0.427,0.473,0.434,0.430,0.700,0.438,-0.330
mean fractal dimension,-0.312,-0.076,-0.261,-0.283,0.585,0.565,0.337,0.167,0.480,1.000,...,-0.051,-0.205,-0.232,0.505,0.459,0.346,0.175,0.334,0.767,0.013
radius error,0.679,0.276,0.692,0.733,0.301,0.497,0.632,0.698,0.303,0.000,...,0.195,0.720,0.752,0.142,0.287,0.381,0.531,0.095,0.050,-0.567
texture error,-0.097,0.386,-0.087,-0.066,0.068,0.046,0.076,0.021,0.128,0.164,...,0.409,-0.102,-0.083,-0.074,-0.092,-0.069,-0.120,-0.128,-0.046,0.008
perimeter error,0.674,0.282,0.693,0.727,0.296,0.549,0.660,0.711,0.314,0.040,...,0.200,0.721,0.731,0.130,0.342,0.419,0.555,0.110,0.085,-0.556
area error,0.736,0.260,0.745,0.800,0.247,0.456,0.617,0.690,0.224,-0.090,...,0.196,0.761,0.811,0.125,0.283,0.385,0.538,0.074,0.018,-0.548
smoothness error,-0.223,0.007,-0.203,-0.167,0.332,0.135,0.099,0.028,0.187,0.402,...,-0.075,-0.217,-0.182,0.314,-0.056,-0.058,-0.102,-0.107,0.101,0.067
compactness error,0.206,0.192,0.251,0.213,0.319,0.739,0.670,0.490,0.422,0.560,...,0.143,0.261,0.199,0.227,0.679,0.639,0.483,0.278,0.591,-0.293
concavity error,0.194,0.143,0.228,0.208,0.248,0.571,0.691,0.439,0.343,0.447,...,0.100,0.227,0.188,0.168,0.485,0.663,0.440,0.198,0.439,-0.254
concave points error,0.376,0.164,0.407,0.372,0.381,0.642,0.683,0.616,0.393,0.341,...,0.087,0.395,0.342,0.215,0.453,0.550,0.602,0.143,0.311,-0.408
symmetry error,-0.104,0.009,-0.082,-0.072,0.201,0.230,0.178,0.095,0.449,0.345,...,-0.077,-0.104,-0.110,-0.013,0.060,0.037,-0.030,0.389,0.078,0.007
fractal dimension error,-0.043,0.054,-0.006,-0.020,0.284,0.507,0.449,0.258,0.332,0.688,...,-0.003,-0.001,-0.023,0.171,0.390,0.380,0.215,0.111,0.591,-0.078
worst radius,0.970,0.353,0.969,0.963,0.213,0.535,0.688,0.830,0.186,-0.254,...,0.360,0.994,0.984,0.217,0.476,0.574,0.787,0.244,0.093,-0.776
worst texture,0.297,0.912,0.303,0.287,0.036,0.248,0.300,0.293,0.091,-0.051,...,1.000,0.365,0.346,0.225,0.361,0.368,0.360,0.233,0.219,-0.457
worst perimeter,0.965,0.358,0.970,0.959,0.239,0.590,0.730,0.856,0.219,-0.205,...,0.365,1.000,0.978,0.237,0.529,0.618,0.816,0.269,0.139,-0.783
worst area,0.941,0.344,0.942,0.959,0.207,0.510,0.676,0.810,0.177,-0.232,...,0.346,0.978,1.000,0.209,0.438,0.543,0.747,0.209,0.080,-0.734
worst smoothness,0.120,0.078,0.151,0.124,0.805,0.566,0.449,0.453,0.427,0.505,...,0.225,0.237,0.209,1.000,0.568,0.519,0.548,0.494,0.618,-0.421
worst compactness,0.413,0.278,0.456,0.390,0.472,0.866,0.755,0.667,0.473,0.459,...,0.361,0.529,0.438,0.568,1.000,0.892,0.801,0.614,0.810,-0.591
worst concavity,0.527,0.301,0.564,0.513,0.435,0.816,0.884,0.752,0.434,0.346,...,0.368,0.618,0.543,0.519,0.892,1.000,0.855,0.533,0.687,-0.660
worst concave points,0.744,0.295,0.771,0.722,0.503,0.816,0.861,0.910,0.430,0.175,...,0.360,0.816,0.747,0.548,0.801,0.855,1.000,0.503,0.511,-0.794
worst symmetry,0.164,0.105,0.189,0.144,0.394,0.510,0.409,0.376,0.700,0.334,...,0.233,0.269,0.209,0.494,0.614,0.533,0.503,1.000,0.538,-0.416
worst fractal dimension,0.007,0.119,0.051,0.004,0.499,0.687,0.515,0.369,0.438,0.767,...,0.219,0.139,0.080,0.618,0.810,0.687,0.511,0.538,1.000,-0.324
target,-0.730,-0.415,-0.743,-0.709,-0.359,-0.597,-0.696,-0.777,-0.330,0.013,...,-0.457,-0.783,-0.734,-0.421,-0.591,-0.660,-0.794,-0.416,-0.324,1.000

In [11]:
# Miramos rápidamente las variables más importantes
from sklearn.ensemble import RandomForestClassifier
import pandas as pd

rf = RandomForestClassifier(random_state=42)
rf.fit(df.drop(columns=['target']), df['target'])

importances = pd.Series(rf.feature_importances_, index=df.columns[:-1])
important_features = importances.sort_values(ascending=False).head(5).index.tolist()

important_features

['worst area',
 'worst concave points',
 'mean concave points',
 'worst radius',
 'worst perimeter']

In [12]:
# import seaborn as sns
# import matplotlib.pyplot as plt

# sns.pairplot(
#     df,
#     hue='target',
#     palette='coolwarm',
#     diag_kind='kde'       # kde en la diagonal
# )

# plt.suptitle('Pairplot de variables importantes diferenciando cáncer vs no cáncer', y=1.02);
# # plt.show()

No se ve absolutamente nada, pero es muy bonito.

In [13]:
df.columns

Index(['mean radius', 'mean texture', 'mean perimeter', 'mean area',
       'mean smoothness', 'mean compactness', 'mean concavity',
       'mean concave points', 'mean symmetry', 'mean fractal dimension',
       'radius error', 'texture error', 'perimeter error', 'area error',
       'smoothness error', 'compactness error', 'concavity error',
       'concave points error', 'symmetry error', 'fractal dimension error',
       'worst radius', 'worst texture', 'worst perimeter', 'worst area',
       'worst smoothness', 'worst compactness', 'worst concavity',
       'worst concave points', 'worst symmetry', 'worst fractal dimension',
       'target'],
      dtype='object')

#### 2. Prueba al menos 5 modelos diferentes de clasificación y aplica un GridSearchCV mediante Pipelines. Aplica también un RandomizedSearchCV.

Modelos que vamos a analizar:

- LogisticRegression

- KNN

- SVC

- RandomForestClassifier

- GradientBoostingClassifier

GridSearchCV mediante Pipelines

In [14]:
from sklearn.model_selection import train_test_split

X = df[['worst area', 'worst concave points', 'mean concave points', 'worst radius', 'worst perimeter']]
y = df['target']


X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

print(X_train.shape)
print(X_test.shape)
print(y_train.shape)
print(y_test.shape)

(455, 5)
(114, 5)
(455,)
(114,)

In [20]:
from sklearn.pipeline import Pipeline
from sklearn.model_selection import GridSearchCV
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

import numpy as np

# -----------------------------
#     Logistic Regression
# -----------------------------
pipe_log = Pipeline(steps=[
    ('imputer', SimpleImputer()),
    ('scaler', StandardScaler()),
    ('log', LogisticRegression(max_iter=500))
])

param_log = {
    'imputer__strategy': ['mean','median'],
    'log__penalty': ['l2'],
    'log__C': np.logspace(0, 4, 10)
}

grid_log = GridSearchCV(pipe_log, param_log, cv=10, scoring='accuracy', n_jobs=-1)


# -----------------------------
#             KNN
# -----------------------------
pipe_knn = Pipeline(steps=[
    ('imputer', SimpleImputer()),
    ('scaler', StandardScaler()),
    ('knn', KNeighborsClassifier())
])

param_knn = {
    'knn__n_neighbors': [3, 5, 7, 9, 11],
    'knn__weights': ['uniform', 'distance']
}

grid_knn = GridSearchCV(pipe_knn, param_knn, cv=10, scoring='accuracy', n_jobs=-1)


# -----------------------------
#             SVC
# -----------------------------
pipe_svm = Pipeline(steps=[
    ('imputer', SimpleImputer()),
    ('scaler', StandardScaler()),
    ('selectkbest', SelectKBest()),
    ('svm', SVC())
])

param_svm = {
    'selectkbest__k': [2, 3, 4],
    'svm__kernel': ['linear', 'rbf', 'sigmoid', 'poly'],
    'svm__C': [0.001, 0.1, 0.5, 1, 5, 10, 100],
    'svm__degree': [1,2,3,4],
    'svm__gamma': ['scale', 'auto']
}

grid_svc = GridSearchCV(pipe_svm, param_svm, cv=10, scoring='accuracy', n_jobs=-1)


# -----------------------------
#        Random Forest
# -----------------------------
pipe_rf = Pipeline(steps=[
    ('imputer', SimpleImputer()),
    ('rndm', RandomForestClassifier())
])

param_rf = {
    'rndm__n_estimators': [70, 100, 130],
    'rndm__max_features': [3, 4, 5, 6],
    'rndm__min_samples_split': [3, 5, 10],
    'rndm__max_depth': [2, 3, 4, 5, 10, 15]
}

grid_rf = GridSearchCV(pipe_rf, param_rf, cv=10, scoring='accuracy', n_jobs=-1)


# -----------------------------
#      Gradient Boosting
# -----------------------------
pipe_gb = Pipeline(steps=[
    ('imputer', SimpleImputer()),
    ('gbc', GradientBoostingClassifier())
])

param_gb = {
    'gbc__n_estimators': [50, 100, 200],
    'gbc__learning_rate': [0.01, 0.05, 0.1, 0.2],
    'gbc__max_depth': [2, 3, 4]
}

grid_gb = GridSearchCV(pipe_gb, param_gb, cv=10, scoring='accuracy', n_jobs=-1)

# Montamos grids
grids = {
    'Logistic Regression': grid_log,
    'KNN': grid_knn,
    'SVC': grid_svc,
    'Random Forest': grid_rf,
    'Gradient Boosting': grid_gb
}

In [ ]:
# Entrenamos los modelos
score = {}
params = {}
estimator = {}
# estimator2 = {}

for nombre, grid in grids.items():
    print(f'Entrenando {nombre}...')
    grid.fit(X_train, y_train)
    # Guardamos resultados
    score[nombre] = grid.best_score_
    params[nombre] = grid.best_params_
    estimator[nombre] = grid.best_estimator_
    # estimator2[nombre] = grid.best_estimator_[nombre]


print(score)
print(params)
print(estimator)
# print(estimator2)

Entrenando Logistic Regression...

c:\Users\urkow\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(

Entrenando KNN...
Entrenando SVC...
Entrenando Random Forest...
Entrenando Gradient Boosting...
{'Logistic Regression': np.float64(0.945054945054945), 'KNN': np.float64(0.9472527472527472), 'SVC': np.float64(0.9494505494505494), 'Random Forest': np.float64(0.945054945054945), 'Gradient Boosting': np.float64(0.9428571428571428)}
{'Logistic Regression': {'imputer__strategy': 'mean', 'log__C': np.float64(7.742636826811269), 'log__penalty': 'l2'}, 'KNN': {'knn__n_neighbors': 7, 'knn__weights': 'uniform'}, 'SVC': {'selectkbest__k': 3, 'svm__C': 0.1, 'svm__degree': 1, 'svm__gamma': 'scale', 'svm__kernel': 'rbf'}, 'Random Forest': {'rndm__max_depth': 4, 'rndm__max_features': 3, 'rndm__min_samples_split': 3, 'rndm__n_estimators': 70}, 'Gradient Boosting': {'gbc__learning_rate': 0.01, 'gbc__max_depth': 2, 'gbc__n_estimators': 100}}
{'Logistic Regression': Pipeline(steps=[('imputer', SimpleImputer()), ('scaler', StandardScaler()),
                ('log',
                 LogisticRegression(C=np.float64(7.742636826811269),
                                    max_iter=500, penalty='l2'))]), 'KNN': Pipeline(steps=[('imputer', SimpleImputer()), ('scaler', StandardScaler()),
                ('knn', KNeighborsClassifier(n_neighbors=7))]), 'SVC': Pipeline(steps=[('imputer', SimpleImputer()), ('scaler', StandardScaler()),
                ('selectkbest', SelectKBest(k=3)),
                ('svm', SVC(C=0.1, degree=1))]), 'Random Forest': Pipeline(steps=[('imputer', SimpleImputer()),
                ('rndm',
                 RandomForestClassifier(max_depth=4, max_features=3,
                                        min_samples_split=3,
                                        n_estimators=70))]), 'Gradient Boosting': Pipeline(steps=[('imputer', SimpleImputer()),
                ('gbc',
                 GradientBoostingClassifier(learning_rate=0.01, max_depth=2))])}

In [17]:
best_grids = [(i, j.best_score_) for i, j in grids.items()]

best_grids = pd.DataFrame(best_grids, columns=["Grid", "Best score"]).sort_values(by="Best score", ascending=False)
best_grids

                  Grid  Best score
2                  SVC    0.949451
1                  KNN    0.947253
0  Logistic Regression    0.945055
3        Random Forest    0.945055
4    Gradient Boosting    0.942857

In [18]:
grid_svc.best_estimator_

Pipeline(steps=[('imputer', SimpleImputer()), ('scaler', StandardScaler()),
                ('selectkbest', SelectKBest(k=3)),
                ('svm', SVC(C=0.1, degree=1))])

In [19]:
from sklearn.metrics import accuracy_score

preds = grid_svc.best_estimator_.predict(X_test)
accuracy_score(y_test, preds)

0.9473684210526315

RandomizedSearchCV

In [21]:
from sklearn.pipeline import Pipeline
from sklearn.model_selection import RandomizedSearchCV
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import StandardScaler
from sklearn.feature_selection import SelectKBest
from sklearn.linear_model import LogisticRegression
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier

import numpy as np

# -----------------------------
#     Logistic Regression
# -----------------------------
pipe_log = Pipeline(steps=[
    ('imputer', SimpleImputer()),
    ('scaler', StandardScaler()),
    ('log', LogisticRegression(max_iter=500))
])

param_log = {
    'imputer__strategy': ['mean','median','most_frequent'],
    'log__penalty': ['l2'],
    'log__C': np.logspace(0, 4, 10)
}

grid_log = RandomizedSearchCV(pipe_log, param_log, n_iter = 50, cv=10, scoring='accuracy', n_jobs=-1)


# -----------------------------
#             KNN
# -----------------------------
pipe_knn = Pipeline(steps=[
    ('imputer', SimpleImputer()),
    ('scaler', StandardScaler()),
    ('knn', KNeighborsClassifier())
])

param_knn = {
    'knn__n_neighbors': [3, 5, 7, 9, 11],
    'knn__weights': ['uniform', 'distance']
}

grid_knn = RandomizedSearchCV(pipe_knn, param_knn, n_iter = 50, cv=10, scoring='accuracy', n_jobs=-1)


# -----------------------------
#             SVC
# -----------------------------
pipe_svm = Pipeline(steps=[
    ('imputer', SimpleImputer()),
    ('scaler', StandardScaler()),
    ('selectkbest', SelectKBest()),
    ('svm', SVC())
])

param_svm = {
    'selectkbest__k': [2, 3, 4],
    'svm__kernel': ['linear', 'rbf', 'sigmoid', 'poly'],
    'svm__C': [0.001, 0.1, 0.5, 1, 5, 10, 100],
    'svm__degree': [1,2,3,4],
    'svm__gamma': ['scale', 'auto']
}

grid_svc = RandomizedSearchCV(pipe_svm, param_svm, n_iter = 50, cv=10, scoring='accuracy', n_jobs=-1)


# -----------------------------
#        Random Forest
# -----------------------------
pipe_rf = Pipeline(steps=[
    ('imputer', SimpleImputer()),
    ('rndm', RandomForestClassifier())
])

param_rf = {
    'rndm__n_estimators': [70, 100, 130],
    'rndm__max_features': [3, 4, 5, 6],
    'rndm__min_samples_split': [3, 5, 10],
    'rndm__max_depth': [2, 3, 4, 5, 10, 15]
}

grid_rf = RandomizedSearchCV(pipe_rf, param_rf, n_iter = 50, cv=10, scoring='accuracy', n_jobs=-1)


# -----------------------------
#      Gradient Boosting
# -----------------------------
pipe_gb = Pipeline(steps=[
    ('imputer', SimpleImputer()),
    ('gbc', GradientBoostingClassifier())
])

param_gb = {
    'gbc__n_estimators': [50, 100, 200],
    'gbc__learning_rate': [0.01, 0.05, 0.1, 0.2],
    'gbc__max_depth': [2, 3, 4]
}

grid_gb = RandomizedSearchCV(pipe_gb, param_gb, n_iter = 50, cv=10, scoring='accuracy', n_jobs=-1)

# Montamos grids
grids = {
    'Logistic Regression': grid_log,
    'KNN': grid_knn,
    'SVC': grid_svc,
    'Random Forest': grid_rf,
    'Gradient Boosting': grid_gb
}

In [22]:
# Entrenamos los modelos
score = {}
params = {}
estimator = {}
# estimator2 = {}

for nombre, grid in grids.items():
    print(f'Entrenando {nombre}...')
    grid.fit(X_train, y_train)
    # Guardamos resultados
    score[nombre] = grid.best_score_
    params[nombre] = grid.best_params_
    estimator[nombre] = grid.best_estimator_
    # estimator2[nombre] = grid.best_estimator_[nombre]


print(score)
print(params)
print(estimator)
# print(estimator2)

Entrenando Logistic Regression...

c:\Users\urkow\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_search.py:324: UserWarning: The total space of parameters 30 is smaller than n_iter=50. Running 30 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(
c:\Users\urkow\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\linear_model\_logistic.py:1135: FutureWarning: 'penalty' was deprecated in version 1.8 and will be removed in 1.10. To avoid this warning, leave 'penalty' set to its default value and use 'l1_ratio' or 'C' instead. Use l1_ratio=0 instead of penalty='l2', l1_ratio=1 instead of penalty='l1', and C=np.inf instead of penalty=None.
  warnings.warn(
c:\Users\urkow\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_search.py:324: UserWarning: The total space of parameters 10 is smaller than n_iter=50. Running 10 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(

Entrenando KNN...
Entrenando SVC...
Entrenando Random Forest...
Entrenando Gradient Boosting...

c:\Users\urkow\AppData\Local\Programs\Python\Python311\Lib\site-packages\sklearn\model_selection\_search.py:324: UserWarning: The total space of parameters 36 is smaller than n_iter=50. Running 36 iterations. For exhaustive searches, use GridSearchCV.
  warnings.warn(

{'Logistic Regression': np.float64(0.9471980676328503), 'KNN': np.float64(0.945024154589372), 'SVC': np.float64(0.9493719806763286), 'Random Forest': np.float64(0.9494685990338164), 'Gradient Boosting': np.float64(0.9472946859903383)}
{'Logistic Regression': {'log__penalty': 'l2', 'log__C': np.float64(21.544346900318832), 'imputer__strategy': 'mean'}, 'KNN': {'knn__weights': 'uniform', 'knn__n_neighbors': 5}, 'SVC': {'svm__kernel': 'rbf', 'svm__gamma': 'scale', 'svm__degree': 3, 'svm__C': 0.5, 'selectkbest__k': 4}, 'Random Forest': {'rndm__n_estimators': 130, 'rndm__min_samples_split': 10, 'rndm__max_features': 5, 'rndm__max_depth': 2}, 'Gradient Boosting': {'gbc__n_estimators': 100, 'gbc__max_depth': 2, 'gbc__learning_rate': 0.01}}
{'Logistic Regression': Pipeline(steps=[('imputer', SimpleImputer()), ('scaler', StandardScaler()),
                ('log',
                 LogisticRegression(C=np.float64(21.544346900318832),
                                    max_iter=500, penalty='l2'))]), 'KNN': Pipeline(steps=[('imputer', SimpleImputer()), ('scaler', StandardScaler()),
                ('knn', KNeighborsClassifier())]), 'SVC': Pipeline(steps=[('imputer', SimpleImputer()), ('scaler', StandardScaler()),
                ('selectkbest', SelectKBest(k=4)), ('svm', SVC(C=0.5))]), 'Random Forest': Pipeline(steps=[('imputer', SimpleImputer()),
                ('rndm',
                 RandomForestClassifier(max_depth=2, max_features=5,
                                        min_samples_split=10,
                                        n_estimators=130))]), 'Gradient Boosting': Pipeline(steps=[('imputer', SimpleImputer()),
                ('gbc',
                 GradientBoostingClassifier(learning_rate=0.01, max_depth=2))])}

In [23]:
best_grids = [(i, j.best_score_) for i, j in grids.items()]

best_grids = pd.DataFrame(best_grids, columns=["Grid", "Best score"]).sort_values(by="Best score", ascending=False)
best_grids

                  Grid  Best score
3        Random Forest    0.949469
2                  SVC    0.949372
4    Gradient Boosting    0.947295
0  Logistic Regression    0.947198
1                  KNN    0.945024

In [24]:
grid_svc.best_estimator_

Pipeline(steps=[('imputer', SimpleImputer()), ('scaler', StandardScaler()),
                ('selectkbest', SelectKBest(k=4)), ('svm', SVC(C=0.5))])

In [25]:
from sklearn.metrics import accuracy_score

preds = grid_svc.best_estimator_.predict(X_test)
accuracy_score(y_test, preds)

0.956140350877193

#### 3. Conclusiones. Guarda el modelo final en un archivo con pickle.

Los dos métodos de búsqueda de hiperparámetros, GridSearchCV y RandomizedSearchCV, dan resultados muy parecidos: los modelos que mejor funcionan son SVC y Random Forest, con una precisión cercana al 95%. Puedo deducir que el conjunto de datos es estable y que el rendimiento no depende de un único conjunto exacto de hiperparámetros, sino de una zona relativamente amplia de valores que aparentemente funcionan bien.

Además, con RandomizedSearchCV he logrado prácticamente el mismo rendimiento que GridSearchCV, pero con la ventaja de haber evaluado menos combinaciones de hiperparámetros, lo que lo convierte en una alternativa más rápida y eficiente cuando el espacio de búsqueda es grande. 

En resumen, ambos métodos coinciden en los mejores modelos, pero RandomizedSearchCV ofrece el mismo resultado con menor coste computacional.

In [ ]:
# Guardamos el mejor modelo en un archivo pickle
# El mejor modelo ha sido
best_model = grid_rf.best_estimator_
best_model.score(X_test, y_test)
import pickle

filename = 'cancer_modeloFinal.pkl' # Es .pkl? No me deja visualizarlo en visual studio

with open(filename, 'wb') as archivo_salida:
    pickle.dump(best_model, archivo_salida)