# Ex1 - Filtering and Sorting Data



### Step 1. Import the necessary libraries

In [7]:
import pandas as pd
import numpy as np

### Step 2. Import the dataset from this [address](https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv) and assign it to a variable called chipo.

In [8]:
url = "https://raw.githubusercontent.com/justmarkham/DAT8/master/data/chipotle.tsv"
chipo = pd.read_csv(url, sep="\t")
chipo

,order_id,quantity,item_name,choice_description,item_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39
1,1,1,Izze,[Clementine],$3.39
2,1,1,Nantucket Nectar,[Apple],$3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98
...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75

In [9]:
chipo.info()

<class 'pandas.DataFrame'>
RangeIndex: 4622 entries, 0 to 4621
Data columns (total 5 columns):
 #   Column              Non-Null Count  Dtype
---  ------              --------------  -----
 0   order_id            4622 non-null   int64
 1   quantity            4622 non-null   int64
 2   item_name           4622 non-null   str
 3   choice_description  3376 non-null   str
 4   item_price          4622 non-null   str
dtypes: int64(2), str(3)
memory usage: 180.7 KB

### Step 3. Name of the max valued product

In [10]:
# Revisamos los diferentes valores de 'item_price'
chipo['item_price'].value_counts()

# Suponemos que todos los precios tienen la misma estructura
# Creamos nueva columna con el precio sin el signo dólar
chipo["price_float"] = chipo["item_price"].str.replace("$", "").astype(float)
chipo

# Buscamos el valor máximo de 'price_float', obtener su índice y buscar en 'item_name'
prod_caro = chipo.loc[(chipo['price_float']/chipo['quantity']).idxmax(), 'item_name']
print('El producto más caro es', prod_caro)

El producto más caro es Steak Salad Bowl

In [11]:
chipo[chipo['item_name'] == 'Steak Salad Bowl']

,order_id,quantity,item_name,choice_description,item_price,price_float
281,123,2,Steak Salad Bowl,"[Tomatillo Red Chili Salsa, [Black Beans, Chee...",$23.78,23.78
606,250,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Pinto Beans, Cheese, Gua...",$11.89,11.89
607,250,1,Steak Salad Bowl,"[Fresh Tomato Salsa, Lettuce]",$9.39,9.39
613,253,2,Steak Salad Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$23.78,23.78
749,309,1,Steak Salad Bowl,"[Roasted Chili Corn Salsa, [Rice, Cheese, Lett...",$11.89,11.89
1159,478,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Rice, Fajita Vegetables,...",$11.89,11.89
1311,534,1,Steak Salad Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$11.89,11.89
1505,612,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Rice, Pinto Beans, Chees...",$11.89,11.89
1571,637,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Sour ...",$11.89,11.89
1590,644,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.89,11.89
1816,734,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Rice, Black Beans, Chees...",$11.89,11.89
2401,953,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Guaca...",$11.89,11.89
2439,969,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.89,11.89
2600,1032,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$9.39,9.39
2624,1042,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Black Beans, Sour Cream,...",$9.39,9.39
2740,1088,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Black...",$11.89,11.89
2804,1114,1,Steak Salad Bowl,"[Tomatillo Red Chili Salsa, [Rice, Black Beans...",$11.89,11.89
2957,1176,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Black Beans, Cheese, Gua...",$11.89,11.89
3098,1235,1,Steak Salad Bowl,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",$9.39,9.39
3120,1244,1,Steak Salad Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$11.89,11.89
3350,1343,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Cheese, Guacamole, Lettu...",$11.89,11.89
3493,1403,1,Steak Salad Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$11.89,11.89
4036,1615,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Chees...",$9.39,9.39
4241,1693,1,Steak Salad Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$9.39,9.39
4313,1720,1,Steak Salad Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$11.89,11.89
4391,1752,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Black Beans, Pinto Beans...",$9.39,9.39
4419,1762,1,Steak Salad Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$9.39,9.39
4547,1807,1,Steak Salad Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$9.39,9.39
4572,1818,1,Steak Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$9.39,9.39

### Step 4. How many products cost more than $10.00?

In [12]:
# Cuento 'item_name' para que no me salgan todas las columnas
# Verifico que en esa columna no hay nulos
print(len(chipo) == chipo['item_name'].count())

# Contar elementos con precio mayor de $10.00
chipo['item_name'][chipo['price_float'] > 10].count()

True

np.int64(1130)

### Step 4.1: Y cuántos pedidos se han hecho con un producto de más de 10$? Es lo mismo?

In [13]:
chipo.head(50)

,order_id,quantity,item_name,choice_description,item_price,price_float
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39,2.39
1,1,1,Izze,[Clementine],$3.39,3.39
2,1,1,Nantucket Nectar,[Apple],$3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98,16.98
5,3,1,Chicken Bowl,"[Fresh Tomato Salsa (Mild), [Rice, Cheese, Sou...",$10.98,10.98
6,3,1,Side of Chips,NaN,$1.69,1.69
7,4,1,Steak Burrito,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$11.75,11.75
8,4,1,Steak Soft Tacos,"[Tomatillo Green Chili Salsa, [Pinto Beans, Ch...",$9.25,9.25
9,5,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Pinto...",$9.25,9.25
10,5,1,Chips and Guacamole,NaN,$4.45,4.45
11,6,1,Chicken Crispy Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$8.75,8.75
12,6,1,Chicken Soft Tacos,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",$8.75,8.75
13,7,1,Chicken Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.25,11.25
14,7,1,Chips and Guacamole,NaN,$4.45,4.45
15,8,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39,2.39
16,8,1,Chicken Burrito,"[Tomatillo-Green Chili Salsa (Medium), [Pinto ...",$8.49,8.49
17,9,1,Chicken Burrito,"[Fresh Tomato Salsa (Mild), [Black Beans, Rice...",$8.49,8.49
18,9,2,Canned Soda,[Sprite],$2.18,2.18
19,10,1,Chicken Bowl,"[Tomatillo Red Chili Salsa, [Fajita Vegetables...",$8.75,8.75
20,10,1,Chips and Guacamole,NaN,$4.45,4.45
21,11,1,Barbacoa Burrito,"[[Fresh Tomato Salsa (Mild), Tomatillo-Green C...",$8.99,8.99
22,11,1,Nantucket Nectar,[Pomegranate Cherry],$3.39,3.39
23,12,1,Chicken Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Tomati...",$10.98,10.98
24,12,1,Izze,[Grapefruit],$3.39,3.39
25,13,1,Chips and Fresh Tomato Salsa,NaN,$2.39,2.39
26,13,1,Chicken Bowl,"[Roasted Chili Corn Salsa (Medium), [Pinto Bea...",$8.49,8.49
27,14,1,Carnitas Burrito,"[[Tomatillo-Green Chili Salsa (Medium), Roaste...",$8.99,8.99
28,14,1,Canned Soda,[Dr. Pepper],$1.09,1.09
29,15,1,Chicken Burrito,"[Tomatillo-Green Chili Salsa (Medium), [Pinto ...",$8.49,8.49
30,15,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39,2.39
31,16,1,Steak Burrito,"[[Roasted Chili Corn Salsa (Medium), Fresh Tom...",$8.99,8.99
32,16,1,Side of Chips,NaN,$1.69,1.69
33,17,1,Carnitas Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$8.99,8.99
34,17,1,Bottled Water,NaN,$1.09,1.09
35,18,1,Chicken Soft Tacos,"[Roasted Chili Corn Salsa, Rice]",$8.75,8.75
36,18,1,Chicken Soft Tacos,"[Roasted Chili Corn Salsa, [Cheese, Lettuce]]",$8.75,8.75
37,18,1,Chips and Guacamole,NaN,$4.45,4.45
38,18,1,Chips and Tomatillo Green Chili Salsa,NaN,$2.95,2.95
39,19,1,Barbacoa Bowl,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$11.75,11.75
40,19,1,Chips,NaN,$2.15,2.15
41,20,1,Chips and Guacamole,NaN,$4.45,4.45
42,20,1,Chicken Bowl,"[Roasted Chili Corn Salsa, [Rice, Black Beans,...",$11.25,11.25
43,20,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Pinto Beans, Chees...",$11.75,11.75
44,20,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75,8.75
45,21,1,Chicken Burrito,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$10.98,10.98
46,21,1,Steak Burrito,"[Tomatillo-Red Chili Salsa (Hot), [Rice, Fajit...",$8.99,8.99
47,21,1,Izze,[Blackberry],$3.39,3.39
48,22,1,Steak Burrito,"[[Fresh Tomato Salsa (Mild), Roasted Chili Cor...",$8.99,8.99
49,22,1,Chips and Guacamole,NaN,$3.99,3.99

In [14]:
# En un mismo pedido podría haber más de un producto de más de 10$
# Contamos número de pedidos que contengan al menos un producto de más de 10$
num_pedidos = chipo['order_id'][chipo['price_float'] > 10].nunique()

print('Hay', num_pedidos, 'pedidos con al menos un producto de más de 10$')

Hay 863 pedidos con al menos un producto de más de 10$

### Step 4.2: Y cuántos pedidos se han hecho de más de 10$? Es lo mismo?

In [15]:
# Para un mismo order_id, la suma de todos los precios debe ser mayor que 10$

# Agrupamos los pedidos, sumando los precios de los productos y los contamos
num_pedidos2 = chipo.groupby('order_id')['price_float'].sum().count()

print('Hay', num_pedidos2, 'pedidos de más de 10$')

Hay 1834 pedidos de más de 10$

### Step 4.3: Y en cuántos pedidos se ha pagado más de 10$ por un mismo producto? Es lo mismo?

In [16]:
# Buscar pedidos con productos con el mismo nombre que sumen más de 10$

# Pro pedido, agrupamos los mismos productos y sumamos los precios para cada producto
pedidos3 = (chipo.groupby(['order_id', 'item_name'])['price_float']
            .sum()
            .reset_index())

# Buscamos los pedidos que tengan algún producto que sume más de 10$
num_pedidos_10 = pedidos3['order_id'][pedidos3['price_float'] > 10].count()

print('Hay', num_pedidos_10, 'pedidos donde un mismo un producto sume más de 10$')

Hay 1167 pedidos donde un mismo un producto sume más de 10$

### Step 5. What is the price of each item and name it unit_price. Get only item_name and unit_price

In [17]:
# Según lo que entiendo, ya lo he hecho en el primer punto
# La última columna 'price_float' equivale a 'unit_price'
chipo['unit_price'] = chipo['price_float'] / chipo['quantity']
chipo

,order_id,quantity,item_name,choice_description,item_price,price_float,unit_price
0,1,1,Chips and Fresh Tomato Salsa,NaN,$2.39,2.39,2.39
1,1,1,Izze,[Clementine],$3.39,3.39,3.39
2,1,1,Nantucket Nectar,[Apple],$3.39,3.39,3.39
3,1,1,Chips and Tomatillo-Green Chili Salsa,NaN,$2.39,2.39,2.39
4,2,2,Chicken Bowl,"[Tomatillo-Red Chili Salsa (Hot), [Black Beans...",$16.98,16.98,8.49
...,...,...,...,...,...,...,...
4617,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Black Beans, Sour ...",$11.75,11.75,11.75
4618,1833,1,Steak Burrito,"[Fresh Tomato Salsa, [Rice, Sour Cream, Cheese...",$11.75,11.75,11.75
4619,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$11.25,11.25,11.25
4620,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Lettu...",$8.75,8.75,8.75
4621,1834,1,Chicken Salad Bowl,"[Fresh Tomato Salsa, [Fajita Vegetables, Pinto...",$8.75,8.75,8.75

In [18]:
chipo[['item_name','unit_price']]

                                  item_name  unit_price
0              Chips and Fresh Tomato Salsa        2.39
1                                      Izze        3.39
2                          Nantucket Nectar        3.39
3     Chips and Tomatillo-Green Chili Salsa        2.39
4                              Chicken Bowl        8.49
...                                     ...         ...
4617                          Steak Burrito       11.75
4618                          Steak Burrito       11.75
4619                     Chicken Salad Bowl       11.25
4620                     Chicken Salad Bowl        8.75
4621                     Chicken Salad Bowl        8.75

[4622 rows x 2 columns]

### Step 6. Sort by the name of the item

In [19]:
chipo_ord = chipo.sort_values('item_name', ascending=True)
chipo_ord

,order_id,quantity,item_name,choice_description,item_price,price_float,unit_price
3389,1360,2,6 Pack Soft Drink,[Diet Coke],$12.98,12.98,6.49
341,148,1,6 Pack Soft Drink,[Diet Coke],$6.49,6.49,6.49
1849,749,1,6 Pack Soft Drink,[Coke],$6.49,6.49,6.49
1860,754,1,6 Pack Soft Drink,[Diet Coke],$6.49,6.49,6.49
2713,1076,1,6 Pack Soft Drink,[Coke],$6.49,6.49,6.49
...,...,...,...,...,...,...,...
2384,948,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa, [Fajita Vegetables,...",$8.75,8.75,8.75
781,322,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Black Beans, Cheese, Sou...",$8.75,8.75,8.75
2851,1132,1,Veggie Soft Tacos,"[Roasted Chili Corn Salsa (Medium), [Black Bea...",$8.49,8.49,8.49
1699,688,1,Veggie Soft Tacos,"[Fresh Tomato Salsa, [Fajita Vegetables, Rice,...",$11.25,11.25,11.25
1395,567,1,Veggie Soft Tacos,"[Fresh Tomato Salsa (Mild), [Pinto Beans, Rice...",$8.49,8.49,8.49

### Step 7. What was the quantity of the most expensive item ordered? 2 ways

In [26]:
# Recuperamos el nombre del producto más caro
producto_caro = chipo.loc[chipo['unit_price'].idxmax(), 'item_name']

# Calcula la suma de la cantidad de ese producto en diferentes pedidos
veces_pedido7 = chipo.loc[chipo['item_name'] == producto_caro, 'quantity'].sum()

print('El producto con el mayor precio unitario se ha vendido', veces_pedido7, 'veces.')

El producto con el mayor precio unitario se ha vendido 31 veces.

In [ ]:
# Ordenar la lista de mayor a menor 'unit_price' y nos quedamos con el producto

producto_caro2 = chipo.nlargest(1, "unit_price")["item_name"].iloc[0]
producto_caro2
veces_pedido7_2 = chipo[chipo["item_name"] == producto_caro2]["quantity"].sum()

print('El producto con el mayor precio unitario se ha vendido', veces_pedido7_2, 'veces.')

'Steak Salad Bowl'

### Step 8. How many times was a Veggie Salad Bowl ordered?

In [31]:
ventas_veggie = chipo.loc[chipo['item_name'] == 'Veggie Salad Bowl']['quantity'].sum()

print('Se han vendido', ventas_veggie, 'Veggie Salad Bowl.')

Se han vendido 18 Veggie Salad Bowl.

### Step 9. How many times did someone order more than one Canned Soda?

In [42]:
# Nos quedamos con ventas de 'Canned Soda' agrupadas por cantidad vendida
ventas_canned = (chipo[chipo['item_name'] == 'Canned Soda']
                 .groupby('order_id')['quantity']
                 .sum())

# Buscamos los pedidos con más de 1 'Canned Soda'
pedidos_soda = (ventas_canned > 1).sum()
print('Hay', pedidos_soda, 'pedidos con más de 1 Canned Soda')

Hay 24 pedidos con más de 1 Canned Soda